export const guideSlugs = [
  "how-to-measure-flour-correctly",
  "packed-vs-loose-brown-sugar",
  "why-density-matters-in-cooking",
  "cup-vs-ml-us-vs-metric",
  "why-honey-weight-varies",
  "butter-solid-vs-melted-weight",
  "oil-density-temperature-effect",
  "why-sifting-changes-flour-weight",
  "measuring-sticky-ingredients",
  "common-cooking-measurement-mistakes",
];

export const chartSlugs = [
  "flour-conversion-chart",
  "sugar-conversion-chart",
  "butter-conversion-chart",
  "honey-conversion-chart",
  "milk-conversion-chart",
  "oil-conversion-chart",
  "rice-conversion-chart",
  "oats-conversion-chart",
  "salt-conversion-chart",
  "cocoa-powder-conversion-chart",
  "brown-sugar-conversion-chart",
  "bread-flour-conversion-chart",
  "cake-flour-conversion-chart",
  "coconut-oil-conversion-chart",
  "maple-syrup-conversion-chart",
  "peanut-butter-conversion-chart",
  "cornmeal-conversion-chart",
  "cornstarch-conversion-chart",
  "chocolate-chips-conversion-chart",
  "quinoa-conversion-chart",
];

export const chartByIngredient: Record<string, string> = {
  "all-purpose-flour": "flour-conversion-chart",
  "granulated-sugar": "sugar-conversion-chart",
  "butter": "butter-conversion-chart",
  "honey": "honey-conversion-chart",
  "whole-milk": "milk-conversion-chart",
  "olive-oil": "oil-conversion-chart",
  "white-rice-long-grain": "rice-conversion-chart",
  "rolled-oats": "oats-conversion-chart",
  "salt-table": "salt-conversion-chart",
  "cocoa-powder": "cocoa-powder-conversion-chart",
  "brown-sugar": "brown-sugar-conversion-chart",
  "bread-flour": "bread-flour-conversion-chart",
  "cake-flour": "cake-flour-conversion-chart",
  "coconut-oil": "coconut-oil-conversion-chart",
  "maple-syrup": "maple-syrup-conversion-chart",
  "peanut-butter": "peanut-butter-conversion-chart",
  "cornmeal": "cornmeal-conversion-chart",
  "cornstarch": "cornstarch-conversion-chart",
  "chocolate-chips": "chocolate-chips-conversion-chart",
  "quinoa": "quinoa-conversion-chart",
};

export const guideByIngredient: Record<string, string> = {
  "all-purpose-flour": "how-to-measure-flour-correctly",
  "bread-flour": "why-sifting-changes-flour-weight",
  "cake-flour": "why-sifting-changes-flour-weight",
  "whole-wheat-flour": "how-to-measure-flour-correctly",
  "brown-sugar": "packed-vs-loose-brown-sugar",
  "light-brown-sugar": "packed-vs-loose-brown-sugar",
  "dark-brown-sugar": "packed-vs-loose-brown-sugar",
  "honey": "why-honey-weight-varies",
  "butter": "butter-solid-vs-melted-weight",
  "butter-melted": "butter-solid-vs-melted-weight",
  "olive-oil": "oil-density-temperature-effect",
  "vegetable-oil": "oil-density-temperature-effect",
  "canola-oil": "oil-density-temperature-effect",
  "coconut-oil": "oil-density-temperature-effect",
  "coconut-oil-melted": "oil-density-temperature-effect",
  "avocado-oil": "oil-density-temperature-effect",
  "sesame-oil": "oil-density-temperature-effect",
  "peanut-oil": "oil-density-temperature-effect",
  "maple-syrup": "measuring-sticky-ingredients",
  "molasses": "measuring-sticky-ingredients",
  "corn-syrup": "measuring-sticky-ingredients",
  "golden-syrup": "measuring-sticky-ingredients",
  "simple-syrup": "measuring-sticky-ingredients",
  "condensed-milk": "measuring-sticky-ingredients",
  "water": "cup-vs-ml-us-vs-metric",
  "whole-milk": "cup-vs-ml-us-vs-metric",
  "skim-milk": "cup-vs-ml-us-vs-metric",
  "chicken-broth": "cup-vs-ml-us-vs-metric",
  "vegetable-broth": "cup-vs-ml-us-vs-metric",
  "lemon-juice": "cup-vs-ml-us-vs-metric",
  "orange-juice": "cup-vs-ml-us-vs-metric",
};

export const categoryGuides: Record<string, string[]> = {
  baking: ["why-sifting-changes-flour-weight", "common-cooking-measurement-mistakes"],
  dairy: ["cup-vs-ml-us-vs-metric", "common-cooking-measurement-mistakes"],
  "oils-fats": ["oil-density-temperature-effect", "why-density-matters-in-cooking"],
  sweeteners: ["measuring-sticky-ingredients", "why-density-matters-in-cooking"],
  grains: ["why-density-matters-in-cooking", "common-cooking-measurement-mistakes"],
  "nuts-seeds": ["why-density-matters-in-cooking", "common-cooking-measurement-mistakes"],
  liquids: ["cup-vs-ml-us-vs-metric", "why-density-matters-in-cooking"],
  spices: ["common-cooking-measurement-mistakes", "why-density-matters-in-cooking"],
};

export const variantSlugsByBase: Record<string, string[]> = {
  "all-purpose-flour": ["all-purpose-flour-sifted", "all-purpose-flour-scooped"],
  "bread-flour": ["bread-flour-sifted", "bread-flour-scooped"],
  "brown-sugar": ["brown-sugar-packed", "brown-sugar-loose"],
  "butter": ["butter-solid"],
  "salt-kosher": ["salt-kosher-diamond-crystal", "salt-kosher-morton"],
  "rolled-oats": ["rolled-oats-dry"],
  "quick-oats": ["quick-oats-dry"],
};
