export type Guide = {
  slug: string;
  title: string;
  description: string;
  body: string[];
  tryLinks: Array<{ label: string; href: string }>;
  related: string[];
};

export const guides: Guide[] = [
  {
    slug: "how-to-measure-flour-correctly",
    title: "How to measure flour correctly",
    description: "Why flour measurement technique matters, and how to get consistent results.",
    body: [
      "<p>Flour is the most common source of recipe inconsistency. The difference between a light, spooned cup and a compact, scooped cup can be 20–30% of the total flour weight. That gap is enough to turn a tender cake into a dense one or a chewy cookie into a dry crumb. The goal is not to obsess over perfection but to reduce surprise. A consistent method gives consistent results.</p>",
      "<p>The most reliable approach is a kitchen scale. Weighing bypasses packing and humidity variables. When a recipe calls for cups, you can still translate to grams with known densities. For example, a level cup of all-purpose flour typically weighs around 125 g, while a cup of bread flour is slightly heavier.</p>",
      "<p>If you are using cups, use the spoon-and-level method. Fluff the flour, spoon it into the cup without shaking, and level with a straight edge. Avoid packing the flour with a scoop or tapping the cup on the counter. Those actions can add many grams without you realizing it.</p>",
      "<p>Different flours behave differently. Cake flour is milled finer and contains less protein, so it sits lighter in a cup. Whole wheat flour has more bran and germ, which makes it heavier. A single measuring technique applied across flours still produces different weights, so it’s useful to check the specific conversion page for the flour you are using.</p>",
      "<p>Humidity matters too. Flour absorbs moisture from the air, which raises its weight slightly. The effect is smaller than the scoop-versus-spoon difference, but it can add up over many cups. If you bake often, store flour in an airtight container and allow it to acclimate to your kitchen before measuring.</p>",
      "<p>When recipes specify “sifted flour,” it usually means you should sift after measuring by volume. This matters because sifting can reduce the density by as much as 10–15%. If the recipe author is expecting that lighter flour and you scoop directly from the bag, the dough will be too dry.</p>",
      "<p>For quick conversions in a pinch, use tablespoons or teaspoons. Small measures are easier to level consistently, and the error is smaller. A tablespoon of flour varies less in absolute grams than a full cup. That makes it easier to scale or troubleshoot a recipe without big swings.</p>",
      "<p>When you’re converting cups to grams, pick one method and stick with it. Switching between spooned and scooped flour mid-recipe is the fastest way to drift off target. Consistency is more valuable than a theoretical “perfect” number.</p>",
      "<p>Use flour conversions as a guide, not a strict rule. Different brands and milling styles can vary. Start with a typical density, then adjust based on how the dough or batter feels. A consistent system turns “close enough” into reliable.</p>",
      "<p>Quick checklist for a consistent cup:</p>",
      "<ul><li>Fluff the flour before measuring.</li><li>Spoon into the cup without tapping.</li><li>Level with a straight edge.</li><li>Avoid scooping directly from the bag.</li></ul>",
      "<p>If you’re ever unsure, weigh once and record the grams you used. You can then reuse that number for the same brand or recipe and remove guesswork entirely. That’s the fastest way to lock in repeatable results.</p>",
      "<p>Numericano provides a reference point so you can keep your results predictable. Pick a method, stick with it, and let the conversions do the rest.</p>",
    ],
    tryLinks: [
      { label: "All-purpose flour: cup → g", href: "/cooking/all-purpose-flour/cup-to-g/" },
      { label: "Bread flour: cup → g", href: "/cooking/bread-flour/cup-to-g/" },
      { label: "Tablespoon → g", href: "/cooking/all-purpose-flour/tbsp-to-g/" },
    ],
    related: ["why-sifting-changes-flour-weight", "common-cooking-measurement-mistakes", "why-density-matters-in-cooking"],
  },
  {
    slug: "packed-vs-loose-brown-sugar",
    title: "Packed vs loose brown sugar",
    description: "Why brown sugar packing changes weight and how to measure it consistently.",
    body: [
      "<p>Brown sugar is sticky, moist, and full of air pockets. The way you fill the cup can change the weight by a surprising amount. A loosely filled cup can be 25% lighter than a firmly packed cup. Recipes that rely on brown sugar for texture or sweetness can swing wildly if you switch between these methods.</p>",
      "<p>“Packed” means you press the sugar into the cup until it holds its shape when turned out. This is the standard assumption in most North American baking recipes. It accounts for the air that would otherwise sit between the crystals.</p>",
      "<p>Loose brown sugar is common when people scoop quickly or when the sugar is especially soft and clumpy. In that case, the cup contains more air and less sugar by weight. If a recipe doesn’t specify, assume packed. That is the baseline in professional recipe testing and most cookbook standards.</p>",
      "<p>Use the conversion pages to see the difference: brown sugar cup to grams uses the packed default, while the loose variant shows the lighter density. The difference shows up even in small measures, like tablespoons and teaspoons.</p>",
      "<p>Humidity plays a role. Brown sugar dries out over time, which makes it lighter and less compressible. Adding a slice of bread or a brown sugar softener can restore moisture and make packing easier. If your brown sugar is very dry and grainy, the packed method will still yield less weight than a moist batch.</p>",
      "<p>Light and dark brown sugars have different molasses content, which changes weight slightly. Dark brown sugar is denser and heavier per cup. If a recipe specifies light or dark, it’s best to stick to that version rather than substituting and guessing.</p>",
      "<p>When scaling a recipe, measuring by weight is the simplest solution. Use grams and a scale to avoid the packed vs loose debate entirely. If you must use volume, be intentional: pack the cup every time or keep it consistently loose.</p>",
      "<p>For quick checks, look at tablespoon conversions. A packed tablespoon of brown sugar is a small, reliable unit and easier to level. It also makes it easier to scale up or down without changing your technique.</p>",
      "<p>Brown sugar also behaves differently in the bowl. Packed sugar brings more sweetness and moisture, which affects chewiness in cookies and the spread in cakes. Loose sugar can make batters drier and reduce caramel notes. If your bake feels off, the packing method is one of the first things to check.</p>",
      "<p>Numericano treats packed as the default because that’s how most recipes are tested. If you prefer the loose method, use the variant conversion pages so your numbers match your technique.</p>",
      "<p>Quick checklist for brown sugar:</p>",
      "<ul><li>If the recipe says “packed,” compress firmly until the cup holds its shape.</li><li>If it doesn’t specify, assume packed for best alignment with common recipes.</li><li>For maximum consistency, weigh instead of measuring by volume.</li></ul>",
      "<p>Once you pick a method, stick to it across a recipe. Changing from loose to packed mid-way is the fastest way to drift from the intended sweetness and moisture levels.</p>",
    ],
    tryLinks: [
      { label: "Brown sugar: cup → g", href: "/cooking/brown-sugar/cup-to-g/" },
      { label: "Brown sugar (loose)", href: "/ingredients/brown-sugar-loose/" },
      { label: "Tablespoon → g", href: "/cooking/brown-sugar/tbsp-to-g/" },
    ],
    related: ["common-cooking-measurement-mistakes", "why-density-matters-in-cooking", "measuring-sticky-ingredients"],
  },
  {
    slug: "why-density-matters-in-cooking",
    title: "Why density matters in cooking",
    description: "Density is the bridge between volume and weight. Here’s how it affects real recipes.",
    body: [
      "<p>Volume is convenient, but weight is consistent. Density is the missing link that explains why a cup of flour does not weigh the same as a cup of sugar, and why a cup of honey is heavier than a cup of water. Understanding density makes your conversions reliable and your recipes repeatable.</p>",
      "<p>Density is simply weight per volume, usually expressed in grams per milliliter. If you know the density of an ingredient, you can convert from cups, tablespoons, or teaspoons into grams. That conversion is what turns “1 cup” into a number you can compare across ingredients and across brands.</p>",
      "<p>Consider two common baking staples: flour and granulated sugar. Flour is airy and traps a lot of air between particles, so it weighs less per cup. Granulated sugar is heavier because the crystals settle tightly.</p>",
      "<p>Density also explains why the same ingredient can have different conversions. Brown sugar is heavier when packed, lighter when loose, and light or dark brown sugar is heavier still because of additional molasses. The ingredient is the same, but the density changes with packing and moisture.</p>",
      "<p>Liquids feel simple, yet they have densities too. Water is close to 1.0 g/mL, which is why many cooks remember that 1 cup of water is about 236 g. But oils are lighter, while syrups are heavier. Using water’s density for everything will skew your conversions.</p>",
      "<p>Temperature matters. Butter is a classic example: a cup of solid butter weighs less than a cup of melted butter because the melted form fills the air gaps. Coconut oil behaves similarly, changing density as it moves from solid to liquid. If your recipe specifies melted or solid, that is a density clue.</p>",
      "<p>Density matters for seasoning too. A tablespoon of table salt can be almost twice the weight of a tablespoon of kosher salt because the crystals are different sizes. That’s a density difference, not a taste difference.</p>",
      "<p>When you build a measurement system around density, you gain consistency. You can scale recipes accurately, swap ingredients confidently, and troubleshoot recipes that are too dry or too wet. If you bake often, you’ll start to recognize that small density differences compound over multiple cups.</p>",
      "<p>Numericano aims to make density practical. You don’t need to memorize every number. Use the ingredient pages and conversion tables for quick, realistic values, then adjust with experience. Over time you’ll find your preferred brands and methods.</p>",
      "<p>Density is not a theoretical detail; it’s the reason your cookies spread or your cakes rise. If a recipe is not behaving, look at the conversions and ask whether the ingredient density you assumed matches how you measured.</p>",
      "<p>Checklist for density-aware measuring:</p>",
      "<ul><li>Use grams for dry ingredients whenever possible.</li><li>Use ingredient-specific densities for volume-to-weight conversions.</li><li>Match the ingredient state (melted vs solid, packed vs loose).</li><li>Adjust for brands and your own measuring technique.</li></ul>",
      "<p>Density becomes intuitive with repetition. After a few bakes, you’ll see why one cup is not a single number, and you’ll know how to select the right conversion quickly.</p>",
    ],
    tryLinks: [
      { label: "Flour: cup → g", href: "/cooking/all-purpose-flour/cup-to-g/" },
      { label: "Sugar: cup → g", href: "/cooking/granulated-sugar/cup-to-g/" },
      { label: "Honey: cup → g", href: "/cooking/honey/cup-to-g/" },
    ],
    related: ["cup-vs-ml-us-vs-metric", "butter-solid-vs-melted-weight", "oil-density-temperature-effect"],
  },
  {
    slug: "cup-vs-ml-us-vs-metric",
    title: "Cup vs mL: US vs metric",
    description: "Understanding cup sizes and why milliliters make conversions more reliable.",
    body: [
      "<p>“One cup” sounds universal, but it is not. The US cup is 236.6 mL, while the metric cup is often 250 mL. Australia uses a 250 mL cup as standard. That 5–6% difference is enough to change a recipe’s hydration or sweetness, especially when you measure multiple cups.</p>",
      "<p>Milliliters are consistent. A milliliter is the same everywhere, which is why professional recipes often list weights or mL. When you rely on cups, you must also know which cup is implied.</p>",
      "<p>Numericano uses the US cup by default because the conversion tables are tuned for common US kitchen standards. If you are using a metric cup, adjust by multiplying by 250/236.6. For example, 1 metric cup of water is 250 g, while 1 US cup of water is about 236 g.</p>",
      "<p>For liquids, milliliters are a better choice. They eliminate the cup size ambiguity and work cleanly with density. If you need to convert from mL to grams, use the ingredient’s density. Water is straightforward, but oils and syrups are not.</p>",
      "<p>For dry ingredients, volume is even trickier. A cup of flour in one kitchen can be heavier than a cup of flour in another because of packing and sifting. Using grams bypasses both the cup-size issue and the packing issue.</p>",
      "<p>The teaspoon and tablespoon also vary internationally. The US tablespoon is 14.8 mL, while an Australian tablespoon is 20 mL. That means a “tablespoon” can be 35% larger depending on your location.</p>",
      "<p>If you bake often, a good rule is: weigh dry ingredients, measure liquids in milliliters, and use the recipe’s region to interpret cups. This will reduce surprises and make your results repeatable.</p>",
      "<p>Many international recipes list both cups and grams. When they do, trust the grams. It’s the most precise representation of the recipe developer’s intent. Use cups only when you lack a scale or when the ingredient is forgiving.</p>",
      "<p>When you see “1 cup of milk” in a US recipe, it’s best to think “about 236 mL.” If your measuring cup is metric, aim for 236 mL rather than the full 250. That small adjustment brings the rest of the conversions back into alignment.</p>",
      "<p>Numericano includes mL-to-gram conversions for this reason. With density in hand, you can keep your measurements consistent across regions and avoid confusion between cup systems.</p>",
      "<p>Quick conversion checklist:</p>",
      "<ul><li>US cup: 236.6 mL.</li><li>Metric cup: 250 mL.</li><li>US tablespoon: 14.8 mL.</li><li>Australian tablespoon: 20 mL.</li></ul>",
      "<p>When a recipe mixes systems, convert everything into one system before you start. It’s a small step that prevents compounding errors later in the process.</p>",
    ],
    tryLinks: [
      { label: "Water: cup → mL", href: "/cooking/water/cup-to-ml/" },
      { label: "Olive oil: mL → g", href: "/cooking/olive-oil/ml-to-g/" },
      { label: "Honey: mL → g", href: "/cooking/honey/ml-to-g/" },
    ],
    related: ["why-density-matters-in-cooking", "common-cooking-measurement-mistakes", "measuring-sticky-ingredients"],
  },
  {
    slug: "why-honey-weight-varies",
    title: "Why honey weight varies",
    description: "Honey changes with temperature and moisture, which shifts grams per cup.",
    body: [
      "<p>Honey feels simple: it’s a thick liquid, so you might assume its weight is constant. In practice, honey varies more than most people expect. Temperature, water content, and crystallization all shift the density. That means a cup of honey can weigh different amounts depending on when and how it was measured.</p>",
      "<p>The main factor is temperature. Warm honey flows freely and expands slightly, making it lighter per cup. Cold honey is thicker and slightly denser. The difference is small in a tablespoon, but it adds up over a full cup.</p>",
      "<p>Moisture content also matters. Honey is hygroscopic, meaning it absorbs water from the air. A higher water content lowers density. Commercial honey can vary within a narrow range, but raw or artisan honey can vary more, especially if it has been stored in a humid environment.</p>",
      "<p>Crystallization changes how honey settles. Crystallized honey has tiny sugar crystals suspended in a thicker solution, which can trap air when scooped. A cup of crystallized honey can be slightly lighter than fully liquid honey if you scoop instead of pour.</p>",
      "<p>For the most consistent results, weigh honey instead of measuring by volume. The conversion for honey cup to grams gives a solid baseline, but a scale eliminates the temperature and moisture differences entirely.</p>",
      "<p>Honey’s density is also a reason to avoid substitutions without adjustments. Maple syrup, agave, and corn syrup each have different densities and water content. If a recipe was tested with honey and you swap with another syrup, the weight and moisture will change even if the volume is the same.</p>",
      "<p>If you need a quick fix, use tablespoon conversions. A tablespoon is easier to measure accurately, and the absolute weight variance is smaller.</p>",
      "<p>When honey is an accent—say a drizzle or a glaze—the exact weight matters less. When honey is the primary sweetener or a structural ingredient, weight matters more. Think of honey as both a sweetener and a liquid. Its density shapes both sweetness and hydration.</p>",
      "<p>Numericano uses typical room‑temperature honey density as the default. If your kitchen is much warmer or cooler, expect small deviations. Use the conversion as a guide and adjust based on texture and taste.</p>",
      "<p>To reduce variation, warm the jar gently in warm water for a few minutes, stir to even out the crystals, and pour at eye level. This produces a more uniform cup and avoids trapped air bubbles.</p>",
      "<p>Quick checklist for honey measurements:</p>",
      "<ul><li>Weigh if possible for best consistency.</li><li>If using cups, warm and stir honey first.</li><li>Pour rather than scoop to reduce trapped air.</li><li>Expect small shifts based on temperature.</li></ul>",
      "<p>Understanding honey’s variability helps you troubleshoot. If a cake seems denser or a sauce thicker than expected, check whether your honey was cold, crystallized, or extra moist.</p>",
    ],
    tryLinks: [
      { label: "Honey: cup → g", href: "/cooking/honey/cup-to-g/" },
      { label: "Honey: tbsp → g", href: "/cooking/honey/tbsp-to-g/" },
      { label: "Maple syrup: cup → g", href: "/cooking/maple-syrup/cup-to-g/" },
    ],
    related: ["measuring-sticky-ingredients", "cup-vs-ml-us-vs-metric", "why-density-matters-in-cooking"],
  },
  {
    slug: "butter-solid-vs-melted-weight",
    title: "Butter: solid vs melted weight",
    description: "Why a cup of melted butter weighs more than a cup of solid butter.",
    body: [
      "<p>Butter is one of the clearest examples of why density matters. A cup of solid butter does not weigh the same as a cup of melted butter. The reason is simple: solid butter contains air gaps, while melted butter does not. When butter melts, it settles into a denser volume, which increases grams per cup.</p>",
      "<p>If a recipe specifies “melted butter,” it expects the heavier, denser version. Measuring solid butter and then melting it can leave you short. Conversely, if a recipe expects solid butter and you pour melted butter into the measuring cup, you may add too much fat and moisture.</p>",
      "<p>Look at the conversions for solid butter cup to grams and melted butter cup to grams. The difference is significant, especially when a recipe uses multiple cups. Even for a half cup, the difference can affect texture in cookies and cakes.</p>",
      "<p>Why does this matter in practice? Butter contributes fat, moisture, and structure. In cookies, extra melted butter can increase spread and chewiness. In cakes, it can lead to a heavier crumb. In pastry, the state of butter affects lamination and flakiness.</p>",
      "<p>If you’re using a scale, the solution is easy: weigh the butter in the state called for. If the recipe wants melted butter, melt it and weigh the liquid. If it wants solid butter, weigh the solid sticks or cubes before melting.</p>",
      "<p>When you must use cups, pay attention to the measurement order. For solid butter, cut into pieces and lightly fill the measuring cup without pressing. For melted butter, pour into a liquid measuring cup at eye level. Avoid using a dry cup for melted butter; it is easy to overfill.</p>",
      "<p>Temperature matters too. Butter softens before it melts, and softened butter still contains air pockets. That means “softened” is not the same as “melted.” If the recipe specifically calls for softened butter, use the solid butter conversion as a closer match.</p>",
      "<p>Butter alternatives like margarine or plant-based butter can have slightly different water content. If you substitute, use weight to stay consistent. Density data helps, but ingredient composition can still change the outcome.</p>",
      "<p>Numericano treats solid butter and melted butter as separate entries because they behave differently. Use the specific conversion page that matches your recipe. It takes a few seconds and saves a lot of troubleshooting.</p>",
      "<p>Quick checklist for butter:</p>",
      "<ul><li>Match the recipe’s state (solid, softened, melted).</li><li>Weigh if possible, especially for baking.</li><li>Use a liquid cup for melted butter, dry cup for solid.</li><li>Do not substitute melted for solid without adjusting weight.</li></ul>",
      "<p>Whenever a recipe feels off, check butter measurement first. It is one of the highest-impact ingredients by weight, and the solid vs melted distinction is an easy place for hidden errors.</p>",
    ],
    tryLinks: [
      { label: "Solid butter: cup → g", href: "/cooking/butter/cup-to-g/" },
      { label: "Melted butter: cup → g", href: "/cooking/butter-melted/cup-to-g/" },
      { label: "Butter: tbsp → g", href: "/cooking/butter/tbsp-to-g/" },
    ],
    related: ["why-density-matters-in-cooking", "oil-density-temperature-effect", "common-cooking-measurement-mistakes"],
  },
  {
    slug: "oil-density-temperature-effect",
    title: "Oil density and temperature effects",
    description: "Why oils weigh slightly differently as temperatures change and how to measure them.",
    body: [
      "<p>Oils are liquids, but they are not all the same. Olive oil, canola oil, avocado oil, and sesame oil each have slightly different densities. Temperature also shifts those densities. The differences are small per tablespoon but meaningful across a full cup or large batch.</p>",
      "<p>Oil density decreases as temperature rises. Warm oil expands, so a cup of warm oil weighs slightly less than a cup of cool oil. This is normal physics and also why kitchen measurements can drift in hot environments.</p>",
      "<p>The type of oil matters too. Olive oil is usually around 0.91 g/mL, while neutral vegetable oils hover around 0.92 g/mL. Sesame oil can be slightly higher, and coconut oil changes state entirely as it melts.</p>",
      "<p>Coconut oil deserves special attention because it is solid at cooler temperatures. Solid coconut oil traps air and weighs less per cup. Melted coconut oil is denser. A recipe specifying melted coconut oil expects that heavier, liquid weight.</p>",
      "<p>When you measure oil by volume, pour gently and avoid bubbles. Bubbles take up space without weight, which can lead to a slightly lower weight per cup. This is usually minor, but it’s another reason that weighing can be more accurate for large batches.</p>",
      "<p>If you cook frequently, you’ll notice that oil behaves differently than water. A cup of water weighs about 236 g, but a cup of oil is closer to 215–220 g depending on the oil. That difference affects batters, marinades, and even frying when you scale recipes.</p>",
      "<p>In baking, oil contributes moisture without adding structure. Too much oil can make cakes heavy or greasy, while too little can make them dry. Accurate conversions matter most when you’re replacing butter with oil or scaling recipes up and down.</p>",
      "<p>For savory cooking, the effects are more subtle but still important when you batch cook. A recipe that calls for 1/2 cup oil can be scaled by weight to avoid overshooting. Use the tablespoon conversions if you prefer smaller, more controlled measures.</p>",
      "<p>Temperature adjustments are rarely required in everyday cooking, but being aware of them helps. If you are in a very hot kitchen or using oil warmed for a sauce, expect a tiny decrease in grams per cup.</p>",
      "<p>Numericano uses room‑temperature densities for oils. That is a practical standard for most kitchens. If your oil is solid or very warm, choose the closest conversion or measure by weight to remove the variable entirely.</p>",
      "<p>Quick checklist for oils:</p>",
      "<ul><li>Use room‑temperature oil for best alignment with charts.</li><li>Weigh when accuracy matters.</li><li>Match the oil type; they are close but not identical.</li><li>Choose melted coconut oil conversions for liquid oil.</li></ul>",
      "<p>Once you align temperature and oil type, your conversions become consistent enough for both home cooking and scaled batches.</p>",
    ],
    tryLinks: [
      { label: "Olive oil: cup → g", href: "/cooking/olive-oil/cup-to-g/" },
      { label: "Canola oil: cup → g", href: "/cooking/canola-oil/cup-to-g/" },
      { label: "Coconut oil (melted): cup → g", href: "/cooking/coconut-oil-melted/cup-to-g/" },
    ],
    related: ["butter-solid-vs-melted-weight", "cup-vs-ml-us-vs-metric", "why-density-matters-in-cooking"],
  },
  {
    slug: "why-sifting-changes-flour-weight",
    title: "Why sifting changes flour weight",
    description: "Understand how sifting affects flour volume and why weight is more reliable.",
    body: [
      "<p>Sifting flour adds air and breaks up clumps. That sounds harmless, but it changes how flour settles in a measuring cup. A sifted cup can weigh significantly less than an unsifted cup.</p>",
      "<p>Most flour has been compacted in the bag. If you scoop directly from the bag, you pull in extra flour because the cup compresses it further. If you sift first, you fluff the flour and reduce the amount that fits into the same cup.</p>",
      "<p>This is why recipes often specify “1 cup sifted flour” or “1 cup flour, sifted.” The difference is when the sifting happens. “1 cup sifted flour” means sift, then measure. “1 cup flour, sifted” means measure first, then sift for texture.</p>",
      "<p>When converting between cups and grams, weight is more dependable than volume. A cup of all‑purpose flour can range from roughly 110–140 g depending on technique. That range can make or break a cake.</p>",
      "<p>Use a kitchen scale if you can. If you must measure by volume, use the spoon‑and‑level method: lightly spoon flour into the cup and level it off without tapping. That approximates an average density and is closer to the standard conversions.</p>",
      "<p>On Numericano, the all‑purpose flour conversion page uses a standard kitchen density. If you’re sifting before measuring, expect your flour to be slightly lighter per cup.</p>",
      "<p>For cake flour and pastry flour, sifting matters even more. These flours are finely milled and trap more air. The best practice is always to weigh them instead of relying on a cup measure.</p>",
      "<p>In short: sifting changes volume, which changes weight in a cup. If precision matters, use grams. If a recipe depends on texture, follow its sifting instructions exactly.</p>",
      "<p>When adapting recipes, keep sifting instructions in mind. If you switch between brands or climates, even a small density shift can compound over multiple cups.</p>",
      "<p>Quick checklist for sifting:</p>",
      "<ul><li>“Cup sifted flour” = sift first, then measure.</li><li>“Cup flour, sifted” = measure first, then sift.</li><li>Weigh for best accuracy.</li><li>Use spoon‑and‑level when measuring by volume.</li></ul>",
      "<p>If a recipe feels dry or dense, sifting technique is a common culprit. Adjust by weight once, then reuse your corrected grams for future bakes.</p>",
    ],
    tryLinks: [
      { label: "All‑purpose flour: cup → g", href: "/cooking/all-purpose-flour/cup-to-g/" },
      { label: "Sifted flour density", href: "/ingredients/all-purpose-flour-sifted/" },
      { label: "Scooped flour density", href: "/ingredients/all-purpose-flour-scooped/" },
    ],
    related: ["how-to-measure-flour-correctly", "common-cooking-measurement-mistakes", "why-density-matters-in-cooking"],
  },
  {
    slug: "measuring-sticky-ingredients",
    title: "Measuring sticky ingredients accurately",
    description: "Tips for honey, syrup, molasses, and other sticky ingredients so your measures are consistent.",
    body: [
      "<p>Honey, molasses, and syrups stick to measuring cups and spoons. That means you rarely get the full measured amount into the bowl unless you use a few tricks.</p>",
      "<p>First, lightly oil the measuring cup with a neutral oil or spray. A thin coating reduces sticking and helps the ingredient slide out cleanly. This method is especially helpful for honey and maple syrup.</p>",
      "<p>Second, choose weight when you can. A kitchen scale eliminates the need to scrape sticky ingredients out of a cup. Place your mixing bowl on the scale, tare it, and pour until you hit the target grams.</p>",
      "<p>Temperature also matters. Warm honey flows more easily and will fill a cup more consistently. If you’re measuring by volume, warm the jar slightly in warm water for a smoother pour, but avoid overheating which can change flavor.</p>",
      "<p>Numericano provides conversions for common sticky ingredients. Honey and maple syrup have different densities. Using the right conversion avoids under‑ or over‑sweetening.</p>",
      "<p>Molasses is heavier than honey, and it can cling more aggressively. Weighing is the best option, but if you’re measuring by volume, grease the cup and use a flexible spatula to scrape the last bit out.</p>",
      "<p>For peanut butter or tahini, which are thick and sticky, scoop and level carefully. A scale is far more reliable for these ingredients.</p>",
      "<p>Consistent measuring keeps your recipes repeatable. Sticky ingredients often dominate sweetness and moisture, so small deviations can be noticeable. If you bake frequently, weighing is worth the small setup time.</p>",
      "<p>If you need to measure multiple sticky ingredients, measure the lightest first and the darkest last. Residual syrup or molasses can affect flavor and color if you reuse the same cup without rinsing.</p>",
      "<p>Quick checklist for sticky ingredients:</p>",
      "<ul><li>Lightly grease cups and spoons.</li><li>Prefer weight for consistency.</li><li>Warm gently for smoother pouring.</li><li>Scrape cups with a flexible spatula.</li></ul>",
      "<p>The goal is to get the full measured amount into the bowl. A few seconds of prep often saves an entire batch from being too sweet or too wet.</p>",
      "<p>Once you adopt a system—grease, pour, scrape, weigh—you’ll find sticky ingredients are no harder than flour or sugar. The key is to reduce transfer losses.</p>",
    ],
    tryLinks: [
      { label: "Honey: cup → g", href: "/cooking/honey/cup-to-g/" },
      { label: "Maple syrup: cup → g", href: "/cooking/maple-syrup/cup-to-g/" },
      { label: "Peanut butter: cup → g", href: "/cooking/peanut-butter/cup-to-g/" },
    ],
    related: ["why-honey-weight-varies", "common-cooking-measurement-mistakes", "cup-vs-ml-us-vs-metric"],
  },
  {
    slug: "common-cooking-measurement-mistakes",
    title: "Common cooking measurement mistakes",
    description: "Avoid the most frequent measurement errors and get more reliable results.",
    body: [
      "<p>Most cooking issues come from a few repeated measurement habits. Fixing them makes recipes more consistent and easier to scale.</p>",
      "<p><strong>1) Scooping flour from the bag.</strong> This packs extra flour into the cup. Use spoon‑and‑level or weigh flour instead. The all‑purpose flour conversion page uses a standard density that assumes spoon‑and‑level.</p>",
      "<p><strong>2) Not leveling measuring cups.</strong> A heaping cup can add 10–20% more of an ingredient. Always level dry ingredients with a flat edge, and read liquid measures at eye level.</p>",
      "<p><strong>3) Using liquid cups for dry measures.</strong> Liquid measuring cups are designed for accuracy at a fill line. Dry cups are meant to be filled and leveled. This swap alone can shift results.</p>",
      "<p><strong>4) Ignoring ingredient density.</strong> A cup of sugar and a cup of flour do not weigh the same. If you swap by volume, adjust by weight using the correct conversion page.</p>",
      "<p><strong>5) Measuring sticky ingredients without prep.</strong> Honey, molasses, and syrups cling to cups. Grease the cup or weigh them for better accuracy.</p>",
      "<p><strong>6) Forgetting to tare the scale.</strong> If you weigh ingredients in a bowl, always zero the scale between additions. This keeps each ingredient accurate and prevents compounding errors.</p>",
      "<p><strong>7) Confusing teaspoon and tablespoon.</strong> A tablespoon is three times a teaspoon. Double‑check abbreviations: tsp and Tbsp are not interchangeable.</p>",
      "<p><strong>8) Mixing metric and US units without conversion.</strong> A US cup is 236.6 mL, not 250 mL. Use cup-to-milliliter conversions when a recipe mixes systems.</p>",
      "<p><strong>9) Measuring by packed vs loose without noting it.</strong> Brown sugar and coconut sugar can be packed or loose, which changes weight per cup. Always follow the recipe’s instruction.</p>",
      "<p><strong>10) Scaling recipes by volume only.</strong> If you double a recipe by volume, small errors become large. Weighing ingredients gives you repeatable results at any scale.</p>",
      "<p>When in doubt, weigh. A scale is the most consistent tool in the kitchen. Use Numericano’s conversions to bridge between cups, grams, ounces, and milliliters when you need volume equivalents.</p>",
      "<p>Quick checklist for fewer measurement mistakes:</p>",
      "<ul><li>Use dry cups for dry ingredients and liquid cups for liquids.</li><li>Level every dry measurement.</li><li>Weigh whenever a recipe is sensitive.</li><li>Convert units before you start mixing.</li></ul>",
      "<p>Most mistakes are small but cumulative. Fixing two or three of them usually produces a noticeable improvement in texture and repeatability.</p>",
    ],
    tryLinks: [
      { label: "Flour: cup → g", href: "/cooking/all-purpose-flour/cup-to-g/" },
      { label: "Sugar: cup → g", href: "/cooking/granulated-sugar/cup-to-g/" },
      { label: "Water: cup → mL", href: "/cooking/water/cup-to-ml/" },
    ],
    related: ["how-to-measure-flour-correctly", "packed-vs-loose-brown-sugar", "cup-vs-ml-us-vs-metric"],
  },
];

export const guideSlugs = guides.map((guide) => guide.slug);

export const chartSlugs = [
  "flour-conversion-chart",
  "sugar-conversion-chart",
  "butter-conversion-chart",
  "honey-conversion-chart",
  "milk-conversion-chart",
  "oil-conversion-chart",
  "rice-conversion-chart",
  "oats-conversion-chart",
  "salt-conversion-chart",
  "cocoa-powder-conversion-chart",
  "brown-sugar-conversion-chart",
  "bread-flour-conversion-chart",
  "cake-flour-conversion-chart",
  "coconut-oil-conversion-chart",
  "maple-syrup-conversion-chart",
  "peanut-butter-conversion-chart",
  "cornmeal-conversion-chart",
  "cornstarch-conversion-chart",
  "chocolate-chips-conversion-chart",
  "quinoa-conversion-chart",
];

export const chartByIngredient: Record<string, string> = {
  "all-purpose-flour": "flour-conversion-chart",
  "granulated-sugar": "sugar-conversion-chart",
  "butter": "butter-conversion-chart",
  "honey": "honey-conversion-chart",
  "whole-milk": "milk-conversion-chart",
  "olive-oil": "oil-conversion-chart",
  "white-rice-long-grain": "rice-conversion-chart",
  "rolled-oats": "oats-conversion-chart",
  "salt-table": "salt-conversion-chart",
  "cocoa-powder": "cocoa-powder-conversion-chart",
  "brown-sugar": "brown-sugar-conversion-chart",
  "bread-flour": "bread-flour-conversion-chart",
  "cake-flour": "cake-flour-conversion-chart",
  "coconut-oil": "coconut-oil-conversion-chart",
  "maple-syrup": "maple-syrup-conversion-chart",
  "peanut-butter": "peanut-butter-conversion-chart",
  "cornmeal": "cornmeal-conversion-chart",
  "cornstarch": "cornstarch-conversion-chart",
  "chocolate-chips": "chocolate-chips-conversion-chart",
  "quinoa": "quinoa-conversion-chart",
};

export const guideByIngredient: Record<string, string> = {
  "all-purpose-flour": "how-to-measure-flour-correctly",
  "bread-flour": "why-sifting-changes-flour-weight",
  "cake-flour": "why-sifting-changes-flour-weight",
  "whole-wheat-flour": "how-to-measure-flour-correctly",
  "brown-sugar": "packed-vs-loose-brown-sugar",
  "light-brown-sugar": "packed-vs-loose-brown-sugar",
  "dark-brown-sugar": "packed-vs-loose-brown-sugar",
  "honey": "why-honey-weight-varies",
  "butter": "butter-solid-vs-melted-weight",
  "butter-melted": "butter-solid-vs-melted-weight",
  "olive-oil": "oil-density-temperature-effect",
  "vegetable-oil": "oil-density-temperature-effect",
  "canola-oil": "oil-density-temperature-effect",
  "coconut-oil": "oil-density-temperature-effect",
  "coconut-oil-melted": "oil-density-temperature-effect",
  "avocado-oil": "oil-density-temperature-effect",
  "sesame-oil": "oil-density-temperature-effect",
  "peanut-oil": "oil-density-temperature-effect",
  "maple-syrup": "measuring-sticky-ingredients",
  "molasses": "measuring-sticky-ingredients",
  "corn-syrup": "measuring-sticky-ingredients",
  "golden-syrup": "measuring-sticky-ingredients",
  "simple-syrup": "measuring-sticky-ingredients",
  "condensed-milk": "measuring-sticky-ingredients",
  "water": "cup-vs-ml-us-vs-metric",
  "whole-milk": "cup-vs-ml-us-vs-metric",
  "skim-milk": "cup-vs-ml-us-vs-metric",
  "chicken-broth": "cup-vs-ml-us-vs-metric",
  "vegetable-broth": "cup-vs-ml-us-vs-metric",
  "lemon-juice": "cup-vs-ml-us-vs-metric",
  "orange-juice": "cup-vs-ml-us-vs-metric",
};

export const categoryGuides: Record<string, string[]> = {
  baking: ["why-sifting-changes-flour-weight", "common-cooking-measurement-mistakes"],
  dairy: ["cup-vs-ml-us-vs-metric", "common-cooking-measurement-mistakes"],
  "oils-fats": ["oil-density-temperature-effect", "why-density-matters-in-cooking"],
  sweeteners: ["measuring-sticky-ingredients", "why-density-matters-in-cooking"],
  grains: ["why-density-matters-in-cooking", "common-cooking-measurement-mistakes"],
  "nuts-seeds": ["why-density-matters-in-cooking", "common-cooking-measurement-mistakes"],
  liquids: ["cup-vs-ml-us-vs-metric", "why-density-matters-in-cooking"],
  spices: ["common-cooking-measurement-mistakes", "why-density-matters-in-cooking"],
};

export const variantSlugsByBase: Record<string, string[]> = {
  "all-purpose-flour": ["all-purpose-flour-sifted", "all-purpose-flour-scooped"],
  "bread-flour": ["bread-flour-sifted", "bread-flour-scooped"],
  "brown-sugar": ["brown-sugar-packed", "brown-sugar-loose"],
  "butter": ["butter-solid"],
  "salt-kosher": ["salt-kosher-diamond-crystal", "salt-kosher-morton"],
  "rolled-oats": ["rolled-oats-dry"],
  "quick-oats": ["quick-oats-dry"],
};
